import localFont from 'next/font/local'

import type { Metadata } from 'next'
import { Inter, Roboto_Mono } from 'next/font/google'
import './globals.css'
import Navbar from './components/molecules/navbar/Navbar'

const gtAmericaMonoLight = localFont({
	// src: '../fonts/FaroVariableWeb.woff2',
	src: '../public/fonts/GT-America-Mono-Light.otf',

	variable: '--font-gtAmericaMonoLight',
})

const gtAmericaMonoLightItalic = localFont({
	// src: '../fonts/FaroVariableWeb.woff2',
	src: '../public/fonts/GT-America-Mono-Light-Italic.otf',

	variable: '--font-gtAmericaMonoLightItalic',
})


const inter = Inter({ subsets: ['latin'] })
const robotoMono = Roboto_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			{/* <Head>
				<link rel='stylesheet' href='https://use.typekit.net/wce3qpd.css' />
			</Head> */}
			{/* <body className={robotoMono.className}> */}
			<body className={`${gtAmericaMonoLight.variable} ${gtAmericaMonoLightItalic.variable}`}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
